# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mP_QkgbU-zSQNyLJLl5jwgmtkmfO8yXL
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('crime_data_sample.csv')
df.head()

import pandas as pd

# Load the dataset
df = pd.read_csv('crime_data_sample.csv')

# Preview first 5 rows
df.head()

df.info()

df.isnull().sum()

df.describe()

import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style
sns.set(style="whitegrid")

# Crime count by type
plt.figure(figsize=(8, 5))
plt.title('Crime Count by Type')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.title('Number of Crimes by City')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 8))
plt.title('Distribution of Crime Types')
plt.ylabel('')  # Remove the y-label
plt.tight_layout()
plt.show()